<script setup>
import { computed, ref } from 'vue'
const acids=[{name:'Fórmico',pka:3.75},{name:'Lático',pka:3.86},{name:'Benzoico',pka:4.20},{name:'Acético',pka:4.76}]
const selected=ref(1);const ph=ref(3.86)
const acid=computed(()=>acids[selected.value])
const ionized=computed(()=>{const ratio=10**(ph.value-acid.value.pka);return ratio/(1+ratio)*100})
const neutral=computed(()=>100-ionized.value)
const reading=computed(()=>ph.value<acid.value.pka-1?'Predomina a forma neutra R–COOH':ph.value>acid.value.pka+1?'Predomina o carboxilato R–COO⁻':'As duas formas coexistem em proporções relevantes')
</script>
<template><div class="ph-simulator"><div class="ph-controls"><label>Molécula<select v-model.number="selected" @change="ph=acid.pka"><option v-for="(item,index) in acids" :key="item.name" :value="index">Ácido {{ item.name.toLowerCase() }} · pKa {{ item.pka.toFixed(2) }}</option></select></label><label class="range-label"><span>pH do meio <b>{{ ph.toFixed(1) }}</b></span><input v-model.number="ph" type="range" min="1" max="8" step=".1"/><span class="range-ends"><i>Ácido</i><i>Básico</i></span></label><p class="ph-reading">{{ reading }}</p></div><div class="species-panel"><div class="species-head"><span>Distribuição estimada</span><small>Henderson–Hasselbalch</small></div><div class="species"><article><div class="species-sphere species-sphere--acid">COOH</div><strong>{{ neutral.toFixed(1) }}%</strong><span>Forma neutra</span></article><article><div class="species-sphere species-sphere--ion">COO⁻</div><strong>{{ ionized.toFixed(1) }}%</strong><span>Carboxilato</span></article></div><div class="distribution"><i :style="{width:`${neutral}%`}"></i></div><p><b>Por que importa?</b> A ionização geralmente aumenta a interação com água. Em conservação, a forma não dissociada pode atravessar membranas com maior facilidade; o resultado também depende da concentração e do organismo.</p></div></div></template>
<style scoped>
.ph-simulator{display:grid;grid-template-columns:.72fr 1.28fr;gap:1rem}.ph-controls,.species-panel{padding:1.25rem;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface)}.ph-controls{display:flex;flex-direction:column;gap:1rem}.ph-controls label{color:var(--muted);font:.62rem var(--font-mono);text-transform:uppercase}.ph-controls select{width:100%;margin-top:.4rem;padding:.7rem;border:1px solid var(--line-strong);border-radius:var(--radius-sm);background:var(--bg-2);color:var(--text);font:600 .76rem var(--font-body)}.range-label>span:first-child{display:flex;justify-content:space-between;align-items:center}.range-label b{color:var(--amber);font-size:1rem}.range-label input{width:100%;accent-color:var(--amber)}.range-ends{display:flex;justify-content:space-between;color:var(--muted-2);font-size:.54rem}.ph-reading{margin:auto 0 0;padding:.7rem;border-left:2px solid var(--amber);background:rgba(255,200,87,.05);font-size:.75rem}.species-head{display:flex;justify-content:space-between}.species-head span{font-weight:600}.species-head small{color:var(--muted);font:.57rem var(--font-mono)}.species{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1rem 0}.species article{display:grid;place-items:center}.species-sphere{display:grid;place-items:center;width:88px;aspect-ratio:1;border-radius:50%;font:700 .72rem var(--font-mono);box-shadow:inset -12px -14px 22px rgba(0,0,0,.28)}.species-sphere--acid{background:#ff7c70;color:#39100d}.species-sphere--ion{background:#78c0ff;color:#071b2d}.species strong{margin-top:.45rem;font:700 1.05rem var(--font-mono)}.species article>span{color:var(--muted);font-size:.64rem}.distribution{height:.55rem;overflow:hidden;border-radius:999px;background:var(--blue)}.distribution i{display:block;height:100%;background:var(--red);transition:width .25s ease}.species-panel>p{margin:.9rem 0 0;font-size:.72rem}.ph-simulator select:focus-visible,.ph-simulator input:focus-visible{outline:2px solid var(--amber);outline-offset:2px}
@media(max-width:760px){.ph-simulator{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.distribution i{transition:none}}
</style>
