<script setup>
import { computed, ref } from 'vue'
const derivatives=[
{id:'salt',formula:'R–COO⁻ M⁺',name:'Carboxilato / sal',route:'Neutralização ou saponificação',property:'Forma iônica; geralmente interage melhor com água.',uses:['Sabões','Conservantes como benzoatos','Sistemas tampão']},
{id:'ester',formula:'R–COO–R′',name:'Éster',route:'Ácido + álcool',property:'Remove o H ionizável da carboxila e altera odor, polaridade e reatividade.',uses:['Aromas e solventes','Biodiesel','Poliésteres']},
{id:'amide',formula:'R–CONR′R″',name:'Amida',route:'Derivação com compostos nitrogenados',property:'Ligação estável e polar, muito presente em moléculas biológicas e fármacos.',uses:['Fármacos','Poliamidas','Ligações peptídicas']},
{id:'polymer',formula:'[–R–COO–]ₙ',name:'Polímero',route:'Polimerização de monômeros adequados',property:'Repetição de unidades cria materiais com propriedades macroscópicas.',uses:['PLA','Fibras de poliéster','Embalagens']},]
const activeId=ref('ester');const active=computed(()=>derivatives.find(item=>item.id===activeId.value))
</script>
<template><div class="derivative-map"><div class="derivative-diagram"><div class="acid-core"><small>Ponto de partida</small><b>R–COOH</b><span>Ácido carboxílico</span></div><button v-for="(item,index) in derivatives" :key="item.id" type="button" :class="[`branch-${index}`,{active:activeId===item.id}]" @click="activeId=item.id"><b>{{ item.formula }}</b><span>{{ item.name }}</span></button></div><Transition name="derivative-change" mode="out-in"><article :key="activeId" class="derivative-panel"><p class="panel-label">{{ active.route }}</p><h3>{{ active.name }}</h3><code>{{ active.formula }}</code><p>{{ active.property }}</p><div><span v-for="use in active.uses" :key="use">{{ use }}</span></div></article></Transition></div></template>
<style scoped>
.derivative-map{display:grid;grid-template-columns:1.2fr .8fr;gap:1rem}.derivative-diagram{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:5rem 8rem;min-height:400px;padding:1.2rem}.derivative-diagram::before,.derivative-diagram::after{content:'';position:absolute;z-index:0;top:50%;left:50%;background:var(--line-strong);transform:translate(-50%,-50%)}.derivative-diagram::before{width:65%;height:1px}.derivative-diagram::after{width:1px;height:65%}.acid-core{position:absolute;z-index:2;top:50%;left:50%;display:flex;flex-direction:column;align-items:center;justify-content:center;width:145px;aspect-ratio:1;border:1px solid var(--amber);border-radius:50%;background:var(--surface-2);transform:translate(-50%,-50%);box-shadow:0 0 35px rgba(255,200,87,.12)}.acid-core small{color:var(--muted-2);font:.52rem var(--font-mono)}.acid-core b{margin:.25rem;color:var(--amber);font:.9rem var(--font-mono)}.acid-core span{font-size:.62rem}.derivative-diagram button{position:relative;z-index:1;display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:120px;padding:.8rem;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface);color:var(--muted);cursor:pointer}.derivative-diagram button b{font:.72rem var(--font-mono)}.derivative-diagram button span{margin-top:.3rem;font:600 .65rem var(--font-body)}.derivative-diagram button.active{border-color:var(--blue);background:rgba(111,178,255,.08);color:var(--text)}button:focus-visible{outline:2px solid var(--amber);outline-offset:2px}.derivative-panel{display:flex;flex-direction:column;justify-content:center;padding:1.4rem;border:1px solid var(--line);border-radius:var(--radius-lg);background:var(--bg-2)}.derivative-panel code{align-self:flex-start;padding:.5rem .7rem;border-radius:999px;background:rgba(255,200,87,.08);color:var(--amber);font:.72rem var(--font-mono)}.derivative-panel p:not(.panel-label){font-size:.8rem}.derivative-panel>div{display:flex;flex-wrap:wrap;gap:.4rem}.derivative-panel>div span{padding:.35rem .55rem;border:1px solid var(--line);border-radius:999px;color:var(--text-soft);font-size:.62rem}.derivative-change-enter-active,.derivative-change-leave-active{transition:.2s ease}.derivative-change-enter-from,.derivative-change-leave-to{opacity:0;transform:translateX(8px)}
@media(max-width:820px){.derivative-map{grid-template-columns:1fr}.derivative-diagram{gap:4.5rem 5rem}}@media(max-width:520px){.derivative-diagram{gap:6rem 1rem;min-height:480px;padding:0}.acid-core{width:125px}.derivative-diagram button{min-height:105px}.derivative-diagram::before{width:70%}}@media(prefers-reduced-motion:reduce){.derivative-change-enter-active,.derivative-change-leave-active{transition:none}}
</style>
