<script setup>
import { computed, ref } from 'vue'
import MoleculeShowcase from './MoleculeShowcase.vue'
const props=defineProps({acids:{type:Array,required:true}})
const leftIndex=ref(0);const rightIndex=ref(1)
const left=computed(()=>props.acids[leftIndex.value]);const right=computed(()=>props.acids[rightIndex.value])
function metrics(acid){return[{label:'Fórmula',value:acid.formula3d||acid.formula},{label:'Tamanho',value:`${acid.atomCounts.C} carbono${acid.atomCounts.C>1?'s':''}`},{label:'pKa aproximado',value:acid.comparePka||'—'},{label:'Solubilidade em água',value:acid.solubility||'Depende do meio'},{label:'Região dominante',value:acid.polarRegion||'Carboxila polar'},{label:'Aplicação-síntese',value:acid.usos[0]}]}
const pairs=[{label:'Fórmico × acético',a:0,b:1},{label:'Cítrico × benzoico',a:2,b:4},{label:'Lático × palmítico',a:3,b:5}]
function usePair(pair){leftIndex.value=pair.a;rightIndex.value=pair.b}
</script>
<template><div class="comparator"><div class="pair-presets"><span>Comparações sugeridas</span><button v-for="pair in pairs" :key="pair.label" type="button" @click="usePair(pair)">{{ pair.label }}</button></div><div class="compare-grid"><article><label>Molécula A<select v-model.number="leftIndex"><option v-for="(acid,index) in acids" :key="acid.nome" :value="index" :disabled="index===rightIndex">{{ acid.nome }}</option></select></label><MoleculeShowcase :atoms="left.atoms" :bonds="left.bonds" :view="left.view" :scale="left.scale" :name="left.nome" has3d :molecule-path="left.moleculePath" :formula="left.formula3d||left.formula" :model-name="left.modelName3d||left.nome" :atom-counts="left.atomCounts" /></article><article><label>Molécula B<select v-model.number="rightIndex"><option v-for="(acid,index) in acids" :key="acid.nome" :value="index" :disabled="index===leftIndex">{{ acid.nome }}</option></select></label><MoleculeShowcase :atoms="right.atoms" :bonds="right.bonds" :view="right.view" :scale="right.scale" :name="right.nome" has3d :molecule-path="right.moleculePath" :formula="right.formula3d||right.formula" :model-name="right.modelName3d||right.nome" :atom-counts="right.atomCounts" /></article></div><div class="comparison-table" role="table" aria-label="Comparação de propriedades"><div v-for="(metric,index) in metrics(left)" :key="metric.label" class="comparison-row" role="row"><b>{{ metric.label }}</b><span>{{ metric.value }}</span><span>{{ metrics(right)[index].value }}</span></div></div><p class="compare-note">Valores e classificações são qualitativos ou aproximados. Temperatura, solvente, concentração e estado de ionização podem alterar o comportamento observado.</p></div></template>
<style scoped>
.comparator{padding:1rem;border:1px solid var(--line);border-radius:var(--radius-lg);background:var(--bg-2)}.pair-presets{display:flex;align-items:center;flex-wrap:wrap;gap:.5rem;margin-bottom:1rem}.pair-presets span{margin-right:auto;color:var(--muted);font:.58rem var(--font-mono);text-transform:uppercase}.pair-presets button{padding:.4rem .6rem;border:1px solid var(--line);border-radius:999px;background:var(--surface);color:var(--muted);font:600 .62rem var(--font-body);cursor:pointer}.pair-presets button:hover{border-color:var(--amber);color:var(--amber)}button:focus-visible,select:focus-visible{outline:2px solid var(--amber);outline-offset:2px}.compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.compare-grid article{min-width:0}.compare-grid label{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:.7rem;margin-bottom:.5rem;color:var(--amber);font:.6rem var(--font-mono);text-transform:uppercase}.compare-grid select{min-width:0;padding:.55rem;border:1px solid var(--line);border-radius:var(--radius-sm);background:var(--surface);color:var(--text);font:.72rem var(--font-body)}.compare-grid :deep(.molecule-showcase__viewport){height:220px}.comparison-table{margin-top:1rem;border:1px solid var(--line);border-radius:var(--radius);overflow:hidden}.comparison-row{display:grid;grid-template-columns:.55fr 1fr 1fr;border-bottom:1px solid var(--line)}.comparison-row:last-child{border:0}.comparison-row>*{padding:.65rem .8rem}.comparison-row b{background:var(--surface-2);color:var(--muted);font:600 .6rem var(--font-mono);text-transform:uppercase}.comparison-row span{border-left:1px solid var(--line);color:var(--text-soft);font-size:.7rem}.compare-note{margin:.7rem .3rem 0;color:var(--muted-2);font-size:.62rem}
@media(max-width:760px){.compare-grid{grid-template-columns:1fr}.comparison-row{grid-template-columns:.72fr 1fr 1fr}.comparison-row>*{padding:.55rem;font-size:.62rem}.pair-presets span{width:100%;margin:0}}@media(max-width:420px){.comparison-row{grid-template-columns:1fr 1fr}.comparison-row b{grid-column:1/-1}.comparison-row span:first-of-type{border-left:0}.compare-grid :deep(.molecule-showcase__viewport){height:280px}}
</style>
